/** @typedef {"mainnet" | "sepolia"} Network */

/** @type {Record<Network, { chainId: number; rpc: string; eas: `0x${string}` }>} */
export const NETWORKS = {
  mainnet: {
    chainId: 1,
    rpc: "https://ethereum.publicnode.com",
    eas: "0xA1207F3BBa224E2c9c3c6D5aF63D0eb1582Ce587",
  },
  sepolia: {
    chainId: 11155111,
    rpc: "https://ethereum-sepolia.publicnode.com",
    eas: "0xC2679fBD37d54388Ce493F1DB75320D236e1815e",
  },
};

export const ENS_REGISTRY = "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e";

/** @param {string} alias @param {string} [base] */
export function toEnsSubname(alias, base = "gridz.eth") {
  const clean = alias.trim().toLowerCase().replace(/[^a-z0-9-]/g, "");
  if (!clean) throw new Error("alias must contain at least one letter, digit, or hyphen");
  return `${clean}.${base}`;
}

/** @param {string} text */
export function parseEnvBlock(text) {
  /** @type {Record<string, string>} */
  const out = {};
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq < 1) continue;
    const key = trimmed.slice(0, eq).trim();
    let val = trimmed.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

/** @param {Record<string, string | undefined>} env */
export function buildEnvFiles(env) {
  const root = [
    "# Generated by scripts/bootstrap.mjs — do not commit",
    `GRIDZ_CHAIN_ID=${env.GRIDZ_CHAIN_ID}`,
    `GRIDZ_RPC_URL=${env.GRIDZ_RPC_URL}`,
    `GRIDZ_ENS_RPC_URL=${env.GRIDZ_ENS_RPC_URL}`,
    `GRIDZ_ENS_BASE=${env.GRIDZ_ENS_BASE}`,
    `GRIDZ_ENS_NAME=${env.GRIDZ_ENS_NAME}`,
    `GRIDZ_RESOLVER=${env.GRIDZ_RESOLVER ?? ""}`,
    `EAS_ADDRESS=${env.EAS_ADDRESS}`,
    `CELL_SCHEMA=${env.CELL_SCHEMA ?? ""}`,
    "",
    `DEPLOYER_PRIVATE_KEY=${env.DEPLOYER_PRIVATE_KEY ?? ""}`,
    `ENS_CONTROLLER_PRIVATE_KEY=${env.ENS_CONTROLLER_PRIVATE_KEY ?? env.DEPLOYER_PRIVATE_KEY ?? ""}`,
    `GRIDZ_SIGNER_KEY=${env.GRIDZ_SIGNER_KEY ?? ""}`,
    "",
    `ONECLAW_AGENT_ID=${env.ONECLAW_AGENT_ID ?? ""}`,
    `ONECLAW_AGENT_KEY=${env.ONECLAW_AGENT_KEY ?? env.GRIDZ_ONECLAW_API_KEY ?? ""}`,
    `ONECLAW_ADDRESS=${env.ONECLAW_ADDRESS ?? ""}`,
    `ONECLAW_CHAIN_ID=${env.ONECLAW_CHAIN_ID ?? env.GRIDZ_CHAIN_ID}`,
    `ONECLAW_API_BASE=${env.ONECLAW_API_BASE ?? "https://api.1claw.xyz"}`,
    `ONECLAW_VAULT_ID=${env.ONECLAW_VAULT_ID ?? ""}`,
    `GRIDZ_ONECLAW_API_KEY=${env.GRIDZ_ONECLAW_API_KEY ?? env.ONECLAW_AGENT_KEY ?? ""}`,
    "",
    `GRIDZ_ENS_TEST_KEY=${env.GRIDZ_ENS_TEST_KEY ?? ""}`,
    "",
  ].join("\n");

  const siteUrl = env.NEXT_PUBLIC_SITE_URL ?? "https://gridz.bio";
  const nextApp = [
    "# Generated by scripts/bootstrap.mjs — do not commit",
    `GRIDZ_RPC_URL=${env.GRIDZ_RPC_URL}`,
    `GRIDZ_RESOLVER=${env.GRIDZ_RESOLVER ?? ""}`,
    `GRIDZ_CHAIN_ID=${env.GRIDZ_CHAIN_ID}`,
    `GRIDZ_ENS_BASE=${env.GRIDZ_ENS_BASE}`,
    `NEXT_PUBLIC_GRIDZ_ENS_BASE=${env.GRIDZ_ENS_BASE}`,
    `NEXT_PUBLIC_GRIDZ_RESOLVER=${env.GRIDZ_RESOLVER ?? ""}`,
    `NEXT_PUBLIC_GRIDZ_CHAIN_ID=${env.GRIDZ_CHAIN_ID}`,
    `NEXT_PUBLIC_GRIDZ_RPC_URL=${env.GRIDZ_RPC_URL}`,
    `NEXT_PUBLIC_SITE_URL=${siteUrl}`,
    `NEXT_PUBLIC_SITE_DOMAIN=${env.NEXT_PUBLIC_SITE_DOMAIN ?? "gridz.bio"}`,
    `NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID ?? ""}`,
    `GRIDZ_PG_DSN=${env.GRIDZ_PG_DSN ?? ""}`,
    `EAS_ADDRESS=${env.EAS_ADDRESS ?? ""}`,
    `CELL_SCHEMA=${env.CELL_SCHEMA ?? ""}`,
    "",
  ].join("\n");

  return { root, nextApp };
}
